### ISSUE TITLE
[Bug]: cant run HttpToolkit 

### ISSUE THREAD

**Issue by mandarinka69** [httptoolkit/httptoolkit#494] opened 2023-10-05 14:45 UTC
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open app
2. An error ia appears Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config" 

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows10

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/10532147/b0ff4d66-411c-42f7-9165-54349170a28a)

**Comment by pimterry** [comment] 2023-10-05 14:47
> [x] I have checked for existing reports of this issue

You haven't checked for existing reports - this is clearly a dupe of #481 which contains the exact same error message.

See [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there which will resolve this for you.

In future please check for existing issues before filing new ones! It saves you and everybody else lots of time and hassle.

**Closed by pimterry** 2023-10-05 14:47 UTC
Labels: bug
