### ISSUE TITLE
[Bug]: HTTP ToolKit won't open on my 24.04 Ubuntu machine

### ISSUE THREAD

**Issue by JoshuaShinkle** [httptoolkit/httptoolkit#642] opened 2024-10-09 18:53 UTC
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

I downloaded the newest (1.19.0) deb package and installed it using the Ubuntu gui. Then I navigated to my computer's list of apps and clicked HTTP ToolKit but the application never began running.

### How often does this bug happen?

Every time

### The desktop OS you're using

Ubuntu 24.04

### Details of other apps/devices

NA

### Error screenshot

NA

### Any other info?

I followed steps on the Troubleshooting page as well as installing past releases..still no success.

Also, when running via terminal:
```
LaunchProcess: failed to execvp:
/opt/HTTP
[4672:1009/165435.253633:FATAL:zygote_host_impl_linux.cc(202)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)
```

I can open it via terminal now:
```
$ httptoolkit --no-sandbox
```

**Comment by pimterry** [comment] 2024-10-10 17:29
Hi @JoshuaShinkle, thanks for the report. I think this is a duplicate of #602, so I'll close this. In short: Ubuntu have broken large numbers of apps in 24.04 by tightening a security setting that breaks them, with very limited workarounds available for app developers. Linux Mint and others have rolled the changes back, but Ubuntu hasn't yet. There's more info available upstream in https://github.com/electron/electron/issues/41066.

**Closed by pimterry** 2024-10-10 17:29 UTC
Labels: bug
