### ISSUE TITLE
Double slash in a URL path causes "request was not forwarded" error

### ISSUE THREAD

**Issue by sergey-be** [httptoolkit/httptoolkit#119] opened 2021-01-05 17:42 UTC
When I send a request with a URL that has `//` (double slash) in the path, HTTP Toolkit returns 502 response and shows "This request was not forwarded successfully" error in the request details pane. For example, the following screenshot is a result of this request 
`curl -vs -H "host: wwww.google.com" -o /dev/null --cacert /path/to/httptoolkit/ca.pem https://localhost:8000//search\?q\=http+toolkit`

<img width="1529" alt="HTTP_Toolkit_error" src="https://user-images.githubusercontent.com/22961113/103676844-df42bb00-4f81-11eb-91e5-cfd096b74245.png">

The same error happens if I send the request from a browser. Although double slash might be illegal in a URL path (I couldn't reliably verify that), all HTTP clients I've tried (cURL, Postman, browsers, etc) forgive it and I get a successful 200 response from a host.

### Environment
HTTP Toolkit version: 1.0.2
OS: macOS 11.0.1

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2021-01-05 23:20
Thanks for the report, good find! I can reproduce this as well. It appears to happen only if the path _starts_ with a double slash - double slashes later on are fine as far as I can tell.

There seems to be a fairly clear cause: some parts of internal parsing logic treat `//search` as an absolute URL, rather than a relative one, and so use that instead of the host header when parsing the request, because they incorrect use the WHATWG URL parsing (just like the last example here: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL). Absolute URLs are allowed as request paths for proxying, so a request for `GET http://abc/ HTTP/1.1` really should be sent to `abc`, but a request to the proxy for `GET //abc HTTP/1.1` should treat that as a relative path, not an absolute URL, and use the host header to deduce the target server.

Should be a quick fix, I'll get that sorted now and update this issue once it's released, should be just a day or two.

**Comment by pimterry** [comment] 2021-01-08 00:24
Thanks for reporting this @sergey-be - this is now fixed in the latest server release (v1.1.1). It'll update in the background next time you start the app, and the following run everything should work for you as normal. Thanks again for reporting this, do let me know if you have any other trouble at all.

**Closed by pimterry** 2021-01-08 00:24 UTC
