### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by sandalsoft** [httptoolkit/httptoolkit#36] opened 2019-09-17 00:49 UTC
I'm loving HTTPToolkit, nice work!

One of my main use cases is inspecting/troubleshooting WebSocket connections.   Any plans to support WebSockets in the future?   

The current crop of WebSocket cli clients and browser extensions aren't great, so I think a high quality tool like HTTPToolkit would be very successful.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2019-09-17 11:13
Hi there! Yes, there are definitely plans, but it's not on the short-term agenda quite yet. 

Right now websockets should be supported by the proxy, but simply silently passed through, without appearing in the UI. To get proper inspection support, we'd need to:

* Extend [Mockttp](https://github.com/httptoolkit/mockttp) to announce events when these connections open/send messages/receive messages/close, rather than passing them through silently (see https://github.com/httptoolkit/mockttp/blob/master/src/server/websocket-handler.ts)
* Design a sensible UX for them: should it be a single item in the list of HTTP exchanges that lists all messages from the session in the pane on the right, or a separate item for each message, or some combination or something else?
* Build the required UI, subscribing to the Mockttp events

I'm planning on looking at this myself in the medium-term future, it shouldn't be especially difficult I think.

The big question mark is around the UX: how should websocket connections be shown in the UI? Any suggestions or examples from other tools would be very welcome! :smiley:

**Comment by francislavoie** [comment] 2019-09-25 21:17
> The big question mark is around the UX: how should websocket connections be shown in the UI?

I figure similarly to how Chrome does it. Show the initial websocket connection in the left pane as a normal request, and when clicked/active, have a panel on the right with all the in/out traffic, one row per message

**Comment by tilmans** [comment] 2020-07-13 16:31
Hi, first of all, great work, the mocking is a joy to use.
Unfortunately the Websockets proxying is not working for me, maybe this is due to the fact that it's going against an unexpected port? I see chrome trying to open a connection with wss://mccux:5000 while the main page is at https://mccux(:443). In a normal Chrome session this works just fine, resulting in a 101 Protocol change, in a HTTP Toolkit session it just sits there in "pending" state.

**Comment by pimterry** [comment] 2020-07-13 16:39
Hi Tilman, sure, let me look into that. Can you share the URL for the page that's failing, or some example code I can run in an intercepted browser to reproduce this?

I've just tested with https://websocketstest.com/ and a couple of other test pages in the latest HTTP Toolkit, and websocket proxying still seems to work in general. Definitely sounds like a bug of course, since it works in Chrome normally, but there must be something specific about the request you're making that's throwing it off.

**Comment by tilmans** [comment] 2020-07-13 16:42
I'll try to find a good way to repro it and get back to you.

**Comment by daluu** [comment] 2021-02-04 22:28
I will check by user testing, but in any case, has this been tested for WS/WSS proxy support of Android applications? Not the Chrome browser or webviews on Android but rather native apps using native websocket or websocket libraries, where the app developer has enabled/configured a proxy configuration for the WS/WSS connection. 

We encountered websocket proxying issue on Android from customer report & from research online (but no official documentation for confirmation), seems Android apps by default are not system proxy aware and Android OS does not force route app websocket traffic through the proxy. Android apps themselves must pull the OS proxy config and set it themselves in the websocket connection for the proxy. In any case, it would be nice to confirm if such Android apps (websocket) can proxy through httptoolkit to the actual destination just fine.

**Comment by pimterry** [comment] 2021-02-05 16:27
I'm fairly confident that proxying of websockets works fine on Android. Happily we don't care about proxy support, because Android interception forcibly redirects all HTTP(S) traffic including websockets using an on-device VPN app.

That still comes with the caveats above: they're transparently proxied so that nothing breaks, but you can't yet see or interact with them within HTTP Toolkit.

I have actually just released a version of Mockttp with [the initial changes](https://github.com/httptoolkit/mockttp/commits/98b932bf45a25bf49b516d06c90c2195a65fb27d) required to start building websocket support though! Mockttp can now define rules for websocket handling - initially just including redirection and error injection - which this gives me the framework to build full functionality, and then to build the UI on top of that. Not here yet, but this is definitely making progress :smiley:

**Comment by AJolly** [comment] 2021-11-02 20:02
Following, I'm very much looking for good websocket support + rpc/json modification.

**Comment by nerve-sys** [comment] 2022-04-19 01:35
any news on this?

**Comment by pimterry** [comment] 2022-04-19 09:28
This isn't available today, but there is active development happening behind the scenes to implement this very soon as we speak.

I'm aiming to have read-only support available so you can see WebSocket traffic in the UI within the next couple of months, and full support for adding rules to modify that traffic before the end of the year.

**Comment by nerve-sys** [comment] 2022-04-19 09:31
glad to hear, thanks for the quick response.

**Comment by pimterry** [comment] 2022-06-27 15:52
WebSockets are now live! Read-only for now, but you can see all websocket data that's sent back and forth, with all the same editor features available for normal request & response bodies. This should be a huge boost for websocket debugging :rocket:

If you have HTTP Toolkit installed already, it'll update in the background next time it's started, and the following run you should be able to see WebSocket data.

This is a first release and it's still a little rough round the edges - breakpoints and automated rewriting for websockets is going to come slowly over the next few months too, I'd like to add proper support for common subprotocols (Socket.IO definitely - suggestions for more welcome!) and I have quite a few substantial UI improvements to come later as well.

In the meantime though it's ready to use - give it a go, and please share any feedback you think of or issues you run into here :smiley:

**Comment by MakeShiftArtist** [comment] 2022-08-22 01:52
Just saw this thread, but I have already posted #322.
I can reupload that issue here if you would like

**Comment by pimterry** [comment] 2022-08-29 13:01
> Are we going to get the feature to mock ws requests in the future?

Eventually, yes. As above: that's a work in progress, and it's coming but it will take time and there's other fixes and improvements coming here first too. I'm aiming to have websocket rewriting rules available before the end of the year.

**Comment by eirikc** [comment] 2022-09-06 09:06
> > Are we going to get the feature to mock ws requests in the future?
> 
> Eventually, yes. As above: that's a work in progress, and it's coming but it will take time and there's other fixes and improvements coming here first too. I'm aiming to have websocket rewriting rules available before the end of the year.

Just an FYI, the UI makes it seem possible to mock websocket requests, but they are all untouched by any rules set. I bought Pro to block websocket requests with the mock feature, but I see now that it's not implemented yet? :) 

<img width="746" alt="image" src="https://user-images.githubusercontent.com/73201653/188593563-91855545-456b-4c9b-8396-cce47a39b424.png">

**Comment by pimterry** [comment] 2022-09-08 15:15
The core websocket rule support described above is now live :tada: 

Just select 'Any WebSocket' (at the bottom of the list) when you start configuring a rule, and you can add then add additional matching conditions for the websocket (effectively the same as HTTP) and handling behaviour (quite different - currently just the options shown above).

Similarly there's also a new default rule, that defines the initial default websocket behaviour, just matching all unmatched websockets and forwarding them to the given target. You can modify that too, or remove it entirely if you'd like.

All these rules only affect _new_ websockets, created after you change the rules. Any existing websockets keep following the behaviour that was configured when they initially connected.

**Comment by pimterry** [comment] 2023-07-10 11:55
WebSocket interception support and the core of rewriting rules was completed quite a while ago, and all that core functionality is live & quite stable now, so I'm going to close this.

There are two major extensions I'd still like to add in future, which I've separated out into separate issues to track more clearly. If you're interested in WebSockets & these features, do please add :+1: to help prioritise the next steps here!

* https://github.com/httptoolkit/httptoolkit/issues/445
* https://github.com/httptoolkit/httptoolkit/issues/446

**Closed by pimterry** 2023-07-10 11:55 UTC
