### ISSUE TITLE
Capture for all ports (and all kinds of data)

### ISSUE THREAD

**Issue by zupd** [httptoolkit/httptoolkit#606] opened 2024-07-16 12:34 UTC
I have noticed that HTTP toolkit doesnt include/shows all types of requests / data being sent (like for example what mitmproxy does). If its a protocol that HTTP toolkit doesnt have a parser for it wont show up. Is there a way to just include all types of traffic to every single port and if its a protocol not supported, just show it as raw binary data (this could be an option to enable which is disabled by default).

I also noticed that it doesnt show HTTP requests to unusual ports. For example I had an app which sent a response to e.g. port 34231, but it never showed up in the UI, so appartently it doesnt capture traffic for all ports but only 80 and 443? Havent really investigated this much, but thats my experiences so far at least.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by zupd** [comment] 2024-07-16 12:36
Sorry, this might be similar to #8 but idk?

**Comment by pimterry** [comment] 2024-07-16 13:19
> I have noticed that HTTP toolkit doesnt include/shows all types of requests / data being sent 

Intercepting non-HTTP traffic is hard to do well, and not the focus of this project (as the name suggests :smile:). It's harder because HTTP has a built-in and widely-supported proxy mechanism, and has reliable in-band signalling for the target destination of each request (i.e. every request has a `Host` header, and TLS connections additionally have SNI information) so that when we intercept an HTTP request, it's always possible to know the final destination we're forwarding it to.

That's not true for non-HTTP traffic. If HTTP Toolkit receives an unrecognized TCP packet, it has no idea and no way to find out where to send it, or what to do next. To avoid that, you need some kind of out-of-band mechanism for signalling, such as real VPN server & client (note that the Android ADB integration uses VPN APIs, but is not actually a VPN) which very significantly complicates things, and isn't always easy to integrate for many targets (e.g. to intercept a single process on your computer).

Is this something you're interested in for a concrete use case? Can you share some examples of the traffic you're looking at? 

In general, there are all sorts of tradeoffs here, and I'm certainly open to exploring options, but right now the main priority is doing HTTP & related specific protocols (websockets, webrtc, eventually QUIC & webtransport) really well, instead of trying to be a general-purpose network analyzer. I think this use case is _much_ more common than the general-purpose unknown-protocol traffic case, and other tools like Wireshark already do low-level arbitrary protocol analysis really well anyway (but with tradeoffs, making them much less effective for quick & easy HTTP debugging etc).

> I also noticed that it doesnt show HTTP requests to unusual ports

HTTP Toolkit can intercept traffic to any port. From this, it sounds like you're using the Android ADB interception option, is that right? That integration captures traffic in two ways:

* It sets the device HTTP proxy, which will capture all HTTP traffic (on all ports) from well-behaved apps who use the device settings (e.g. anybody using standard Android APIs to send requests).
* It uses the VPN APIs to monitor all packets, and forcibly redirect packets to recognized destination ports to HTTP Toolkit (defaults [here](https://github.com/httptoolkit/httptoolkit-android/blob/54aaa4b34f4f7d40cb67a450e40e4e554ab13538/app/src/main/java/tech/httptoolkit/android/PortListActivity.kt#L12-L16)), which captures recognizable HTTP-like traffic from even badly-behaved (or actively interception-resistant) apps.

The goal in this case is to avoid capturing non-HTTP traffic, because we won't be able to forward that on (as above) and in this case we're intercepting the whole device so we want to avoid breaking unrelated apps & traffic. You can configure this though - to do so, connect your device to HTTP Toolkit, and then click the ports option that's shown inside the HTTP Toolkit Android app to add extra ports that will be matched by that VPN redirection logic.

Alternatively, you can use the Android Frida-powered integration option that was added recently. This targets a single app, and captures all network connections from that app, HTTP or not. Non-HTTP traffic will break, but since it's only the traffic from the app you're interested in (rather than all apps on the device) this is less of a concern.

Does that make sense?

**Comment by zupd** [comment] 2024-07-16 14:20
Yeah, I mean it makes sense to only support HTTP related protocols or course. I have been using HTTP toolkit a bit for Android app debugging and reversing. But since some Android apps also uses other protocols (like grpc/protobuf etc for Firebase and similar things) it didnt show up in http toolkit and I had to use something else like mitmproxy. But I have seen a few posts about implementing protocols like that in the future too. The reason why I wanted all traffic was that if I wanted to reverse an Android application I might not know on beforehand which protocol or address/port the app is using to send data, so then you would get a quick overview of what it sent where :)

**Comment by zupd** [comment] 2024-07-16 14:24
For the second question: yes I have been using the VPN variant, which is why I didnt see those requests to other ports :) As I said earlier, my use case is that I do not know which port the app might use beforehand, so thats why I wanted to capture it to see what it used. I havent seen the Frida variant that was added recently but I will check it out. Thank you for the responding so quickly and for clarifying 😄

**Comment by pimterry** [comment] 2024-07-16 14:28
Grpc is built on top of HTTP/2, so that should be fully supported :smile:. Protobuf isn't really a protocol itself, but it's pretty often used on top of HTTP (within grpc and elsewhere) and those cases should be fine as well.

HTTP Toolkit has built-in support for protobuf, and although the tools for grpc specifically are a bit limited all the raw traffic should be intercepted & visible. Do you have any specific examples where that's not working right now?

**Comment by zupd** [comment] 2024-07-16 14:34
> Grpc is built on top of HTTP/2, so that should be fully supported :smile:. Protobuf isn't really a protocol itself, but it's pretty often used on top of HTTP (within grpc and elsewhere) and those cases should be fine as well.
> 
> HTTP Toolkit has built-in support for protobuf, and although the tools for grpc specifically are a bit limited all the raw traffic should be intercepted & visible. Do you have any specific examples where that's not working right now?

Can test when I get home. I wanted to see Firebase messages, and I think those are sent through a single connection that is being kept alive. So whenever the phone is online it starts this connection so that apps can send and receive messages. I guess the issue here is more about supporting streamed requests maybe? I think I saw an issue about that as well

**Comment by pimterry** [comment] 2024-07-16 16:41
Hmm, I'm not sure about the details Firebase connections, but in general it's all HTTP and with the VPN we should definitely be able to capture everything (at least in theory). Happy to look in more detail if you can share examples.

**Comment by nutterthanos** [comment] 2024-10-05 00:29
> HTTP Toolkit has built-in support for protobuf, and although the tools for grpc specifically are a bit limited all the raw traffic should be intercepted & visible. Do you have any specific examples where that's not working right now?

i just figured if you want to send requests with protobuf it won't let you send it as the decoded message and only via text/hex format
besides that protobuf is such an weird format of data which is sorta hard to understand

**Comment by pimterry** [comment] 2024-10-09 13:50
@nutterthanos 

> i just figured if you want to send requests with protobuf it won't let you send it as the decoded message and only via text/hex format
> why is that?
> besides that protobuf is such an weird format of data which is sorta hard to understand

The main issue is that we can make good guesses at the original format of a message without any extra info, but the ways to limit that safely are very very limited. If you want to 100% correctly format or generate a protobuf message, you need the schema.

I'm open to include protobuf schema support in HTTP Toolkit (probably as a Pro feature, where you mainly add schemas via the Pro settings and link them to specific hostnames, and then they're used automatically). That's unlikely to appear in the very short term, but it's definitely something I'd like to include eventually.

I think that's unrelated to this issue though, best to discuss on #44 I think.

This issue was originally tracking traffic that's completely not present in HTTP Toolkit, but no example was shared. I'm going to close it for now - @zupd if you can share steps to reproduce where some connections are completely missing, please do so and I can reopen & investigate further.

**Closed by pimterry** 2024-10-09 13:50 UTC
