### ISSUE TITLE
[Bug]: Permission denied for websockets on e.g. discord.com

### ISSUE THREAD

**Issue by sla-te** [httptoolkit/httptoolkit#363] opened 2022-12-02 16:08 UTC
### Repro steps

Open Chrome/Firefox in the 'intercept' menu. See 403 when attempting to connect to wss://gateway.discord.gg/

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![image](https://user-images.githubusercontent.com/22568014/205335584-b19d809a-591b-4d4b-93ba-afe23171312b.png)
![image](https://user-images.githubusercontent.com/22568014/205335598-7b33b082-8592-46ec-a7cf-fbc91f6ddc39.png)

**Comment by pimterry** [comment] 2022-12-06 11:20
I can reproduce this easily, even just looking at websocket connections on the login page, which connects to `wss://remote-auth-gateway.discord.gg/?v=2` before login successfully in a normal browser, but fails in an intercepted browser. Good find!

I strongly suspect that this is due to Discord trying to detect non-browser clients and block them, and detecting HTTP Toolkit as part of that. We've seen that repeatedly in the past elsewhere for HTTP, although this is the first time I've seen it for websockets.

HTTP Toolkit already includes various mitigations for this (see https://twitter.com/HttpToolkit/status/1565642116298153986) including TLS fingerprint matching and some work to precisely match fingerprintable raw header formatting details when proxying requests, which can cover 100% of HTTP cases that I've seen, but clearly that's not working for these websockets.

I think it's very likely that this is due to header issues, as the WS library we use [doesn't support](https://github.com/websockets/ws/issues/2103) the raw headers API we use to handle parts of this with HTTP, and that's the only real difference between the HTTP & WS requests in this scenario. I've just opened that issue there to track this, and look into adding that later. Once/if that becomes available we should be able to easily extend our logic [here](https://github.com/httptoolkit/mockttp/blob/d1eb9c1a9480a1a319269d54d2101e7e91b4eca8/src/rules/websockets/websocket-handlers.ts#L339-L351) to preserve raw details correctly.

**Comment by shirshak55** [comment] 2022-12-10 06:34
@pimterry it would be nice if we can use QR code system similar to the android app. I don't like messing with wifi proxies because I have to come again to change it :(

**Comment by pimterry** [comment] 2023-01-09 04:22
This was recently fixed in HTTP Toolkit. Your app will automatically update in the background next time it's opened, and the following time this should work correctly. I'm going to close this issue for now, but feel free to reply here or open a new issue if you're still having any other issues.

**Closed by pimterry** 2023-01-09 04:22 UTC
Labels: bug
