### ISSUE TITLE
Certeficate expire

### ISSUE THREAD

**Issue by oRIOnTx** [httptoolkit/httptoolkit#218] opened 2022-01-01 21:31 UTC
Pls fix certeficate expire data. Dates gone after 31.12.2021

**Comment by pimterry** [comment] 2022-01-03 14:52
Thanks for reporting this. I think the issue you're describing was caused by a bug that broke certificate generation date calculations just for 24 hours at the new year.

Everything should be working now that that date has passed though. I'm going to close this issue since it shouldn't appear again, but do let me know if you're still having problems and I'm happy to investigate further.

**Closed by pimterry** 2022-01-03 14:52 UTC

**Comment by oRIOnTx** [comment] 2022-01-03 14:54
Thanks !
