### ISSUE TITLE
Ability to use * regex in the Host HTTPS Whitelist 

### ISSUE THREAD

**Issue by nutterthanos** [httptoolkit/httptoolkit#599] opened 2024-06-18 01:42 UTC
What I would like added was that with the Host HTTPS Whitelist is that I can use * on it essentially an reflex that would if I just put * it would whitelist everything as such and if I did something like *.google.com it would whitelist all google.com subdomains as such since typing each domain in manually is cumbersome

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2024-06-20 15:14
Can you explain more about your use case? Why do you need to whitelist lots of domains?

The HTTPS whitelist is really intended for one-off broken websites or unusual configuration testing, not for widespread wildcard use, since it makes all matching traffic significantly less secure. If you're using an untrusted self-signed or internal CA for example you probably want to trust your CA instead, which will then make HTTP Toolkit traffic work correctly to all websites where that CA is used.

**Comment by nutterthanos** [comment] 2024-06-20 23:51
> Can you explain more about your use case? Why do you need to whitelist lots of domains?

The HTTPS whitelist is really intended for one-off broken websites or unusual configuration testing, not for widespread wildcard use, since it makes all matching traffic significantly less secure. If you're using an untrusted self-signed or internal CA for example you probably want to trust your CA instead, which will then make HTTP Toolkit traffic work correctly to all websites where that CA is used.

all i thought is its for the httptoolkit ca/android app on the device and nothing to do with any other ca and i thought this was to try to bypass ssl pinning

**Comment by pimterry** [comment] 2024-06-21 10:22
Ah, no, that's not what this does. The whitelist affects connections from HTTP Toolkit on your computer to the internet. It doesn't affect connections from apps on your phone to your computer. Does that make sense?

If you're trying to disable certificate pinning, you'll want to use different techniques, see https://httptoolkit.com/blog/frida-certificate-pinning/ for more info (or try the new "Android App via Frida" button in the latest HTTP Toolkit, which automates much of this).

**Comment by nutterthanos** [comment] 2024-06-22 07:57
So it's just for like when I use any option that runs direct on device eg Chrome etc and not like phone through frida etc?

**Comment by pimterry** [comment] 2024-06-24 14:39
> So it's just for like when I use any option that runs direct on device eg Chrome etc and not like phone through frida etc?

No. For every single type of interception there are two connections for each request: one between the client and HTTP Toolkit, and one between HTTP Toolkit and the target server. The HTTPS whitelist only affects the 2nd connection to the target server, it doesn't affect the client. If you want to change how the client trusts certificates, you have to do that within the client itself (e.g. Frida on Android, app modifications, Chrome settings, whatever) although in general HTTP Toolkit does try to do this for you as much as possible.

I'm going to close this issue for now, since I think it's clear that this setting isn't what you want, and adding a * wildcard wouldn't help.

> Also speaking of Frida I clicked on it then it just went into Unavailable or whatever

That sounds like a different issue. Happy to investigate though. If you can reproduce this reliably now, please open a new issue with the details (the device you're using, the steps you're following etc etc), the logs from HTTP Toolkit, and screenshots of any errors or anything else that pops up.

**Closed by pimterry** 2024-06-24 14:39 UTC
