### ISSUE TITLE
[Bug]: Missing slashes when calling prepend-node.js

### ISSUE THREAD

**Issue by victoralvelais** [httptoolkit/httptoolkit#458] opened 2023-08-06 02:07 UTC
### Repro steps

This happens after I start a new terminal or link an existing terminal then try calling npm or yarn. These calls work before I link to the existing terminal.

A particular issue is the missing slashes in the printed location:
`Error: Cannot find module 'C:UsersEisen UchihaAppDataLocalProgramshttptoolkitresourceshttptoolkit-serveroverridesjsprepend-node.js'`

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Details of other apps/devices

Node.js v18.12.1
NPM v8.3.1
Yarn 1.22.19

### Error screenshot

<img width="570" alt="image" src="https://github.com/httptoolkit/httptoolkit/assets/6127592/a4158183-181a-4412-9bd9-defae5fc0234">

### Any other info?

I've had issues with certain programs not resolving the space in my username, so it could be related to that.

**Comment by pimterry** [comment] 2023-08-07 18:06
Hmm, that's very odd. I can't reproduce this myself, and I haven't heard this elsewhere, so there must be something specific about this system or setup that causes this.

Does this happen if you just run `node`?

If you look at `env` after interception, does the `NODE_OPTIONS` variable look reasonable?

It would be interesting to try copying the `js` folder from that path to other locations on your computer (e.g. within paths without spaces) and then updating the NODE_OPTIONS variable to match, and seeing if you can exactly work out what triggers this. I would be a bit surprised if the space is what causes this, since that would be a pretty basic bug in Node.js's option parsing, and the error message clearly has both sides of the space. But anything's possible!

**Comment by victoralvelais** [comment] 2023-08-08 17:34
Hmm, you could be right. The NODE_OPTIONS looks right too, but node becomes inaccessible as well. I get the same issue on two systems, Win10 (Home/Pro).

![image](https://github.com/httptoolkit/httptoolkit/assets/6127592/ae6221b4-0ba6-4d21-8469-6513c4e31b86)

**Comment by pimterry** [comment] 2023-08-09 12:35
Hmm, I'm not sure what you're doing there, but that doesn't look related - I think in this case bash is complaining that `run` doesn't exist, it's not complaining about `node`.

What happens if you just run `node` directly, without that?

The NODE_OPTIONS value does look correct though, and as you can see it's got correct quoting so the spaces shouldn't cause problems. It would definitely be interesting to try moving the `js` directory referenced there elsewhere, updating `NODE_OPTIONS` manually to match, and seeing if this still occurs.

You could also test just setting `NODE_OPTIONS` manually in a terminal with your own JS file with various different values & paths, and see if you can reproduce the same error yourself.

Anything else you can think of to work out what triggers this would be very interesting. I'm fairly confident this works correctly for the general case (there's lots of other people using it) and so there must be something specific to this environment, and it's a matter of working of what exactly that is...

**Comment by victoralvelais** [comment] 2023-08-09 17:03
You're right, I was thinking "run node" at the time so I must have brain tripped. I re-ran that sequence:
<img width="532" alt="image" src="https://github.com/httptoolkit/httptoolkit/assets/6127592/f7cc819f-872d-459d-b7bb-1502e6a3dc27">

And I tried it with the folder moved to the top of the c drive:
<img width="560" alt="image" src="https://github.com/httptoolkit/httptoolkit/assets/6127592/4fa80744-7ce1-4081-8461-c67e61876138">

It turns out that the tools I'm monitoring are communicating over TCP and TLS, so it doesn't suit my use case anyway. Feel free to close this issue if you think this is an outlier.

**Comment by pimterry** [comment] 2023-08-15 19:19
> It turns out that the tools I'm monitoring are communicating over TCP and TLS, so it doesn't suit my use case anyway. Feel free to close this issue if you think this is an outlier.

Ok, fair enough! I'll leave this open in case anybody else runs into this, but I'll stop investigating for now.

If you do find any clues why this might be happening later on, I would be very interested to hear them, I haven't seen anything like this myself and I still can't seem to reproduce this elsewhere. There must be something unique about your terminal environment, but I have no idea what it us! Very mysterious.

**Comment by leumasme** [comment] 2023-09-10 20:50
I initially couldn't reproduce it either in the git bash shell, but I suspected that it was related to the space in your username, and was correct.  
If  
- the shell is git bash
- NODE_OPTIONS contains "--require {a path in quotes}"

this error will occour.  
```
Temm@Temm-PC MINGW64 ~
$ export NODE_OPTIONS="--require \"S:\Afolder\script.js\""

Temm@Temm-PC MINGW64 ~
$ node
node:internal/modules/cjs/loader:1080
  throw err;
  ^
Error: Cannot find module 'S:Afolderscript.js'
```

If the path to `prepend-node.js` contains a space, it will automatically be in quotes, which is why this originally occoured.  
It later occoured when `prepend-node.js` was manually loaded from `C:\js\` because the path was also in quotes.  
Note that this does not happen if the require is passed directly instead of via NODE_OPTIONS.  
Looks like something along the way is interpreting the backslashes in the path as escape operators for the previous character, effectively deleting them.  
Simply replacing "\" with "\\" in the `export` command doesn't work (at least manually), since the export command itself then already replaces the "\\" with "\".
```
Temm@Temm-PC MINGW64 ~
$ export NODE_OPTIONS="--require \"S:\\Afolder\\script.js\""

Temm@Temm-PC MINGW64 ~
$ echo $NODE_OPTIONS
--require "S:\Afolder\script.js"
```
using quadruple backslashes so the env variable has double backslashes solves the issue, but I didn't do much testing.
```
Temm@Temm-PC MINGW64 ~
$ export NODE_OPTIONS="--require \"S:\\\\Afolder\\\\script.js\""

Temm@Temm-PC MINGW64 ~
$ node
Hi
Welcome to Node.js v18.17.1.
Type ".help" for more information.
>
```

**Comment by pimterry** [comment] 2023-09-14 15:31
Thanks for working this out @leumasme! That definitely makes sense.

I've done some further digging, and I think I have a good general solution for this: it turns out that Node doesn't actually care about Windows vs POSIX separators anyway, so we can just use POSIX forward slashes everywhere (`c:/abc` instead of `c:\abc`) and then the slashes are never interpreted as escape characters and this whole problem goes away.

I've just published a server update that should fix this. Next time you run HTTP Toolkit it'll update in the background, and the following time this should work correctly.

I'm going to assume that resolves this issue and close this for now, but if anybody is still facing the issue after updating please do let me know :smile:

**Closed by pimterry** 2023-09-14 15:31 UTC
Labels: bug
