### ISSUE TITLE
Stuck on Loading Response Body for Zstd-encoded bodies

### ISSUE THREAD

**Issue by icoolguy1995** [httptoolkit/httptoolkit#141] opened 2021-05-04 14:24 UTC
Hi there,

I have been trying httptoolkit on android devices. However, there is one issue. The windows application is not printing the response body, if the response is too large. It just keeps on loading. 

Regards

**Comment by pimterry** [comment] 2021-05-14 18:23
Ok, I've done some digging: I can reproduce this, and it's happening because that response is compressed with Facebook's own content encoding called [Zstandard](https://en.wikipedia.org/wiki/Zstandard) (you can see that that https://i.instagram.com/api/v1/feed/timeline/ response has `zstd` in its content-encoding header).

Right now, HTTP Toolkit doesn't recognize that as a content-encoding (it's not common, I've never seen it before!) so it fails to decompress and show the response.

Fixing this is going to require adding some implementation of zstd decompression, which is a bit complicated. Conveniently I'm already planning some unrelated content-encoding improvements though, so I should be able to work on this as part of that. At the very least I'd like to show a better error here, but it looks like there are [some existing libraries](https://github.com/donmccurdy/zstddec) which could be integrated to add full zstd support. I'll explore that and let you know once I've got got something usable.

**Comment by icoolguy1995** [comment] 2021-05-17 04:34
Thank you for your detailed overview. Can you suggest any workaround for the meantime?

**Comment by pimterry** [comment] 2021-05-17 12:00
Unfortunately no! Sorry about that. HTTP Toolkit works almost exclusively on decoded content, since that's where all the useful data is, and it doesn't have any functionality to access the raw Zstandard-compressed data when decoding fails like this. I'll look into build a fallback option for that as part of this, and let you know as soon as something's available.

**Comment by pimterry** [comment] 2021-05-24 17:28
Hi @icoolguy1995 - this is now released! There's a couple of rough edges left to finish which I'll release in the next couple of days (e.g. matching or filtering for bodies that are encoded with zstd) but you can now view Zstd encoded bodies like any other.

Next time you start HTTP Toolkit it'll update in the background, and the following time everything should work as expected. I'm going to close this issue for now, but do let me know if you hit any other problems.

**Closed by pimterry** 2021-05-24 17:28 UTC
