### ISSUE TITLE
Recording the request text after mocking?

### ISSUE THREAD

**Issue by bupt-saddestboy-official** [httptoolkit/httptoolkit#533] opened 2023-12-04 10:06 UTC
I like the tool, but I cannot figure out where to see the request I have mocked (where the text is the one after manually editing). What I can only find is the one before mocking. Is there any way to have a look at the one after mocking?

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2023-12-05 17:24
I think this is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/250.

Right now, the data shown is always from the client perspective (the data the client originally sent, and the final data they receive). In future, we could have a toggle so you can switch between perspectives to handle this. From what you're describing, I think that would work for you? If so, you can add a :+1: to that issue to vote for this. PRs also welcome if you'd like to help build that functionality yourself - let me know if so.

**Closed by pimterry** 2023-12-05 17:24 UTC
