### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by rajwebhost** [httptoolkit/httptoolkit#551] opened 2024-02-16 04:47 UTC
HTTP Toolkit is really awesome tool for intercepting HTTP. I like this very much but one thing miss too much is the native apple silicon support. Currently it's for intel processor. so works over rosetta on apple silicon processor. thus not getting the top performance and it works slowly and consumes more resource. So, it would be great if HTTP Toolkit does support apple silicon processor by native. I hope the developer will soon release native apple silicon supported version of HTTP Toolkit.

Thank you..

**Comment by pimterry** [comment] 2024-02-16 12:34
Hi @rajwebhost, thanks for your feedback, glad you're liking HTTP Toolkit so far. I think this is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/551, so I'll close this issue now, but you can subscribe to that issue or add a :+1: there to vote for it. If you're also interested in helping with development to make this happen, that's very welcome too (note that HTTP Toolkit is free for open-source contributors). You can see the list of next steps on that issue.

**Closed by pimterry** 2024-02-16 12:34 UTC
