### ISSUE TITLE
API response delay option 

### ISSUE THREAD

**Issue by Strategy9062** [httptoolkit/httptoolkit#352] opened 2022-10-31 08:07 UTC
---

We should have an option to delay and api response by a specified amount of time .
This feature is really helpful when we test SPA apps to see what happens if an API call take s a long time to return response 

_Does this affect you too? Click the :smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2022-11-01 17:21
Indeed! I'm definitely interested in this, and there's been some related progress recently as part of other work on WebRTC: you can now add WebRTC rules that include a 'sleep' step while processing the connection.

I'm intending to extend that same model to HTTP and WebSockets soon, but not immediately, so I can't give an ETA on that quite yet.

That said, I am going to close this issue, as it's a duplicate of https://github.com/httptoolkit/httptoolkit/issues/55. Thanks for filing this though - if you are interested in this functionality, you can :+1: on that other issue to vote for it, and you can also subscribe to that issue via GitHub to hear once this is available.

**Closed by pimterry** 2022-11-01 17:21 UTC

**Comment by Strategy9062** [comment] 2022-11-01 18:22
Thanks for the prompt response Tim

Sent from Proton Mail mobile

-------- Original Message --------
