### ISSUE TITLE
Add search response body

### ISSUE THREAD

**Issue by nhokpro** [httptoolkit/httptoolkit#356] opened 2022-11-16 13:31 UTC
I want to find a request that the response has a word. Currently, I can only do the search on a header, query, or request body.
My current workaround is to export the har file and find it with my note pad

**Comment by nhokpro** [comment] 2022-11-16 13:36
> You can search the response body. There's actually no way to search only the request body.
> 
> If you filter for `body*=something` it will search both bodies for all requests. Does that not work for you?

I don't know if I am wrong but I search request body with body*=
and I mean the response body, the content that the requests returned

**Comment by nhokpro** [comment] 2022-11-16 13:39
<title>
    Are you using HTTP Toolkit? Yes!
  </title>
for example, if I want to search "using HTTP" then it should show me the  request

**Comment by pimterry** [comment] 2022-11-16 13:58
Hmmm, I can reproduce this. Interestingly though, only for that specific request. For example,

* `curl amiusing.httptoolkit.tech` in an intercepted terminal.
* `body*=html` returns nothing, not matching the body there as it should - this is a bug.
* `curl example.com` in an intercepted terminal.
* `body*=html` matches the request, and shows it correctly, totally fine.

Are there other requests where you're seeing this?

It's definitely a bug either way, looks like our detection of "this request isn't yet completed" is subtly broken for certain requests for some reason (my best guess is that it's related to how they're handled differently - with a response being injected directly, with no upstream proxying) and so we incorrectly skip the response body in this case.

I'll look into it now, but more examples would be helpful if you have any.

**Comment by pimterry** [comment] 2022-11-16 14:43
Ok, for that specific case this is now fixed - both the visible filtering issue ([here](https://github.com/httptoolkit/httptoolkit-ui/commit/e4992ae65eca6e60472e587745c498eeecde9660)), and the underlying "request not yet considered complete" issue ([here](https://github.com/httptoolkit/mockttp/commit/f591eccc6d04facb7ff4af5bb2847015a9fea874)).

Thanks for reporting this! Good catch. Let me know if you have any other cases I can reproduce where this happens.

**Closed** 2022-11-21 13:39 UTC
