### ISSUE TITLE
[Bug]: Startup failed

### ISSUE THREAD

**Issue by LuizaRomani** [httptoolkit/httptoolkit#489] opened 2023-10-05 12:11 UTC
### Repro steps

1. Open the app
2. the error: Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### How often does this bug happen?

Every time

### The desktop OS you're using

windows 11

### Details of other apps/devices

- using Genymotion Samsung S10 device (Android 11)

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/69905073/959c1846-3b87-4393-9ac7-27f2b373724e)

**Comment by pimterry** [comment] 2023-10-05 12:34
Dupe of #481, see [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there.

**Closed by pimterry** 2023-10-05 12:34 UTC
Labels: bug
