### ISSUE TITLE
[Bug]: start error

### ISSUE THREAD

**Issue by allanrodriguesdev** [httptoolkit/httptoolkit#491] opened 2023-10-05 14:26 UTC
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### How often does this bug happen?

Every time

### The desktop OS you're using

windows 11

**Comment by pimterry** [comment] 2023-10-05 14:28
You haven't checked for existing reports - this is clearly a dupe of #481. See [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there which should resolve this for you..

**Closed by pimterry** 2023-10-05 14:28 UTC
Labels: bug
