### ISSUE TITLE
HTTP Toolkit crashes with ECONNRESET

### ISSUE THREAD

**Issue by tilmans** [httptoolkit/httptoolkit#92] opened 2020-07-31 18:52 UTC
Getting these regularly - let me know if I can grab some logs ...

![2020-07-31 at 20 31](https://user-images.githubusercontent.com/884017/89067465-9ef66580-d36f-11ea-8778-5f708b4b034d.png)

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2020-07-31 18:57
Ah, damn. I'll look into this in just a minute.

The CLI output from the app would be interesting, but steps to reproduce would be even better, if that's possible!

**Comment by pimterry** [comment] 2020-07-31 19:23
Ok, I've rolled back the upgrade here, so that should fix this in the short term. If you've already got the buggy release, next time you open the app it'll downgrade in the background.

I'm not exactly sure what the underlying issue is, but I'll look into it early next week and get this all working properly then. Do let me know if you see any other issues though.

**Comment by pimterry** [comment] 2020-08-03 13:03
@tilmans if you get a sec, any details about the request that causes this (probably the first request that resets in your application when HTTP Toolkit crashes) would be really useful. Especially:

* Is it coming from a browser? Which browser?
* Is it HTTP/HTTPS/WS/WSS?
* Are there any logs from the server that might tell us what the server has responded with up to this point?
* Any console logs in the browser?
* There's a RST being send here - any idea why that might be happening in this case?

I can see from the error reporting that this was hit a few times in a short time, so it must be fairly reliably reproducible, but of course I don't record request details, and the stacktrace is just a ECONNRESET on a TLS connection. I've been manually injecting resets into all sorts of connections at different moments to try and trigger it myself, but I can't seem to recreate it locally.

You won't be able to reproduce it in the app any more (due to the rollback) but you should still be able to do so using the master build directly:

```bash
$ git clone https://github.com/httptoolkit/httptoolkit-server.git
$ npm install
$ npm start

# Then open app.httptoolkit.tech in Chrome
```

**Comment by pimterry** [comment] 2020-08-26 12:41
There was some separate discussion by email, a tested prerelease with fixes, and now a new real release out, and I don't think this specific issue still exists, so I'm going to close it.

That said, if you or anybody else reading this finds a new way to crash the app, do file a new bug and let me know!

**Comment by Nico04** [comment] 2023-03-19 14:33
Hi, I'm having the same issue constantly, I can't use the program.
I have about 1min to use it, then it crashes with this error.
Can't relate to a specific request though. But I'm inspecting a rooted Android emulator via ADB.

**Comment by pimterry** [comment] 2023-03-20 12:53
Hmm, that's very interesting! I'll reopen this.

There must be some specific connection reset case within the proxy itself (within [Mockttp](https://github.com/httptoolkit/mockttp/)) where the error is not being handled right now.

I'd love to fix this, but to do so I need to be able to reproduce it locally. Is there any way you can share more information so I can do that? If that's not possible, you could alternatively try to reproduce it using Mockttp directly yourself (general purpose guide here: https://httptoolkit.com/blog/javascript-mitm-proxy-mockttp/) and see if you can work out where exactly this comes from and open a PR to fix it. Somewhere in there there must be a TLS stream that's initialized without an error handler, but there's quite a few possibilities and it's very hard to confirm that or test a fix without being able to reproduce the scenario manually.

**Closed** 2023-04-25 16:56 UTC

**Comment by alozano-redteam** [comment] 2025-05-14 02:52
@pimterry I have the same issue with the last version, I'm running it as a proxy from my iphone, and it happens when I force close the application, I'm using ionic, so I think it is something related to https or ws.
