### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by NatanielBR** [httptoolkit/httptoolkit#544] opened 2024-01-16 12:31 UTC
Its possible create a tree view tab, to see all requests by host?

**Comment by pimterry** [comment] 2024-01-16 15:21
I think this is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/125.

To answer your question though: no, that's not available yet. For now, the best alternative is to use [the filtering options](https://httptoolkit.com/docs/reference/view-page/#filtering-intercepted-traffic) to filter traffic for specific hosts, but yes I know it doesn't cover all the same use cases.

Doing this properly is definitely an interesting idea though! You can add a :+1: on that issue to vote for it, or contributions in [the UI](https://github.com/httptoolkit/httptoolkit-ui/) working towards building this are very welcome (note that HTTP Toolkit Pro is free for all contributors).

**Closed by pimterry** 2024-01-16 15:21 UTC
