### ISSUE TITLE
the app wont work over environments with VPN 

### ISSUE THREAD

**Issue by mFouadShaheen** [httptoolkit/httptoolkit#117] opened 2020-12-15 08:19 UTC
the app wont work over environments with VPN  and for some reason most of the site I worked with not loading properly or not loading at all 

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2020-12-15 12:47
Hi @mFouadShaheen

> the app wont work over environments with VPN

I assume you're talking about the Android app, not the desktop app?

For Android, yes, the default Android interception setup won't work, as it too uses a VPN, and Android won't allow two at the same time. You can still intercept your Android traffic though! For cases like this, you'll just need to set your proxy settings manually to point to your local HTTP Toolkit IP & port (see 'Anything' in the interception options on the desktop app for more details). You can still use the automatic app setup to install and configure certificates, if that's useful, but you'll then need to disconnect that to connect your separate VPN.

Does that work for you?

> for some reason most of the site I worked with not loading properly or not loading at all

Can you provide any more detail here?

* Which app are you using to load the site? E.g. Chrome on Android, Firefox, a specific app, or something else?
* What phone & OS are you using?
* Is the device rooted, or are you just using user certificates?
* Does anything appear in the HTTP Toolkit desktop app when you are sending requests? E.g. a request with an error code, or a failed HTTPS connection?

**Comment by erhhung** [comment] 2021-03-25 22:11
I just discovered this tool and was very eager to try it out on my Mac. After a quick install via Homebrew, I launched the app, and macOS popped up the dialog asking me whether I trust this app—all standard flow.

After that, however, I saw nothing appear, not even the menu bar. This stayed stalled for over a minute, and then a window appeared along with the app menu bar, but that window is 100% white/empty. I waited a couple more minutes and still saw nothing, so I closed the window and then manually quit the app from the menu bar. It was a rather disappointing FTUX after I was sold on all the cool features... I reran the app several times but encountered the same behavior, so I gave up, until...

Since I'm on my company's VPN all day I didn't think much, until I realized that that was probably the cause. After shutting down the Cisco VPN client, Voila! the app window launched immediately with the spinning "connected sources". I exit the app and reconnected to the VPN, then relaunch the app, and this time it started up as usual... So there's a critical dependency on an Internet connection on the very first launch.

When I selected a browser to intercept—MS Edge in my case—the new window appears and immediately gets stuck on https://amiusing.httptoolkit.tech/. That page eventually loads after a couple of minutes. While most requests seem to work and return 200, a bunch from some CDNs and fonts.googleapis.com all return 502 timeouts. After I disconnect from the VPN, all page loads run successfully and quickly (without having to restart the app or the browser session), so the app definitely isn't too fond of VPN connections and handling of auto-proxy config (i.e. reading wpad.dat).

Is it possible, like many apps, to explicitly have the user enter standard HTTP/S proxy settings, including the no_proxy list?

Version: 1.2.1
OS: macOS 10.15.7

**Comment by pimterry** [comment] 2021-03-29 10:49
This is another useful data point, thanks @erhhung. It's surprising though - while HTTP Toolkit doesn't yet automatically use an external proxy, it should work with a VPN in every other way, as long as the VPN routes traffic like normal. If the VPN blocks all outgoing traffic except traffic via its proxy of course then we'll have trouble. Does that sound likely in your case?

If so, it sounds like this is more closely linked to #57 than this issue (which is about android on-device VPNs).

This is definitely something I'd like to support eventually anyway. It doesn't work today partly because there's not that much demand that I've seen yet, but also because we can't automatically use the system proxy settings since in many cases people configure the system proxy to be HTTP Toolkit itself, and that loop is obviously problematic :smile:. That's resolvable though, it just needs either in-app configuration or clever proxy loop detection.

The Edge behaviour you describe is interesting, because that means that in your case our Edge intercept isn't setting the Edge proxy properly somehow... For https://amiusing.httptoolkit.tech/, the page should load immediately because its mocked inside HTTP Toolkit itself. It's just a localhost request and response that doesn't go to the outside network, which when intercepted should be instant. When it loads eventually, does it show the "you're being intercepted" page, or the big red "you're not being intercepted" page?

**Comment by erhhung** [comment] 2021-03-31 00:17
@pimterry, it wasn't clear that the OP addressed this issue w.r.t. the Android app since there was no confirmation, but, regardless, #57 definitely applies, and is sorely needed for me and, I believe, in common corporate environments that:

1. Use a VPN client (e.g. Cisco VPN Client) that routes `0.0.0.0/0` (all traffic) through the tunnel
2. Require the use of an HTTP proxy for all external traffic

As for the initial browser intercept page, I looked a little more carefully, and, yes, after a minute or so, the page does show "You're being intercepted by HTTP Toolkit". The trace does show that the initial GET https://amiusing.httptoolkit.tech/ returns 200 immediately, but the HTML content was delayed rendering because it tried to load `https://fonts.googleapis.com/css?family=Lato` and `https://amiusing.httptoolkit.tech/favicon.ico`, both timed out with 502s. Depending on the browser, there are also a bunch of other failed requests to *.google.com or *.msn.com, etc. without doing anything.

**Comment by erhhung** [comment] 2021-05-25 23:38
Any update from the priority side of things? I see #135 is also related to this.

**Comment by pimterry** [comment] 2021-05-28 23:16
It's making progress. I've now [mostly implemented](https://github.com/httptoolkit/mockttp/commits/4695a5d904a2e300eb9f887c62009fe72259a9c6) proxy support in Mockttp, which will support all the internal HTTP forwarding logic required to proxy our intercepted requests on elsewhere. As far as I can tell that's working for normal requests, HTTP/2 & WebSockets already, when given a specific proxy configuration to use.

This still needs quite a bit of work to do cross-platform proxy detection that can reliably populate that configuration without setting up proxy loops, UI to tweak config for advanced cases, and changes to the initial app loading to support proxies there, but I think the hardest part is sorted now. Watch this space!

**Comment by erhhung** [comment] 2021-05-29 00:21
Thanks for the update. It looks like, as you said, with a given proxy configuration, you've got it all working. I don't think you need to do any auto-proxy configuration using `.pac` files or `wpad.dat` files. I think for most people's needs, the Docker Desktop config for proxy is perfect:

![image](https://user-images.githubusercontent.com/5808864/120052210-0190b000-bfd9-11eb-8c91-442b363de21e.png)

**Comment by pimterry** [comment] 2021-06-17 15:31
Hey @erhhung quick update: this should now work :smiley:. The manual configuration UI is still in progress and it's all a little experimental, but HTTP Toolkit should now load itself and forward intercepted traffic via the system proxy automatically (as long as it's not a localhost proxy, in which case it'll be ignored to avoid loops).

This affects some structural internals, so you'll need to reinstall HTTP Toolkit to get full support. When you have a minute, could you download the latest version from httptoolkit.tech, reinstall, and let me know if it works for you?

**Comment by erhhung** [comment] 2021-06-18 18:03
Hi @pimterry, I install version 1.4.1 via Homebrew, but it does not appear to work when I'm connected via VPN.

This is my normal system proxy configuration:
![image](https://user-images.githubusercontent.com/5808864/122598807-2dc0af00-d022-11eb-98e8-abb3e492a92b.png)
I normally do not enable Web Proxy or Secure Web Proxy settings explicitly since Automatic Proxy Configuration takes care of that whether I'm on VPN or not.

Although, for the purpose of this test, I did also enable those settings, but it still does't work.
![image](https://user-images.githubusercontent.com/5808864/122599404-2cdc4d00-d023-11eb-87b1-729ccbf9e299.png)
The initial "you're being intercepted" page takes 30 seconds to appear because Google fonts cannot be loaded (502 error).

I also tried launching the app from the command-line, where I usually have the trio `http_proxy`, `https_proxy`, and `no_proxy` variables defined. I was hoping that the child process launched via CLI would use those env vars, even if subsequently launching an intercepted terminal would override those env vars.

I'm not sure how you're determining the upstream proxy, but if it's based on values akin to those three env vars, then I'd strongly recommend using those if found in the env vars when HTTP Toolkit is launched. Of course, once you have the configuration UI completed, that will take precedence.

**Comment by pimterry** [comment] 2021-06-21 13:43
> I install version 1.4.1 via Homebrew

Ah, sorry - the correct version for the fixed release is 1.4.2, not 1.4.1.

Homebrew is only occasionally updated so its often slightly outdated. It'll be at least a few more days until it's available there I expect, sorry. You will always get the latest build if you download the DMG directly instead though. This normally doesn't matter since the app internals self-update directly from source in the background when the app runs, so an outdated build from homebrew functions the same after the first run, but there's some required changes to the desktop shell that aren't automatically updated in this case unfortunately.

You can download the latest DMG build from [httptoolkit.tech](https://httptoolkit.tech/) or directly from the GitHub releases: https://github.com/httptoolkit/httptoolkit-desktop/releases.

Can you test again with 1.4.2 and let me know if it works for you?

> I normally do not enable Web Proxy or Secure Web Proxy settings explicitly since Automatic Proxy Configuration takes care of that whether I'm on VPN or not.

Right now, HTTP Toolkit doesn't support PAC files and it only supports specific proxy configuration, but that is in my roadmap too, it's just more complicated. For now to test this you will need to manually set at least one of the HTTP, HTTPS or SOCKS proxy values.

> I'm not sure how you're determining the upstream proxy

I've done quite a bit of work on this now, and bundled up a set of reusable packages ([cross-platform](https://github.com/httptoolkit/os-proxy-config), [mac](https://github.com/httptoolkit/mac-system-proxy), and [windows](https://github.com/httptoolkit/windows-system-proxy)) so hopefully others can do this more easily in future.

In the Mac case, these use the standard [scutil](https://ss64.com/osx/scutil.html) command to read the system proxy settings, by running `scutil --proxy` and parsing the output. That directly reports the system configuration as set in that Mac config UI. Meanwhile the `*_proxy` env vars are used on Linux (where that's the closest to standard proxy config that's available), while Windows reads the system settings from the registry.

**Comment by pimterry** [comment] 2021-07-01 12:47
I'm fairly confident now that this functionality works. It's working correctly everywhere I've tested, and while that's not going to be representative of 100% of environments it does mean it should work in most places!

The Pro proxy configuration UI is also now available, for advanced use cases:

![Screenshot from 2021-06-24 20-21-59](https://user-images.githubusercontent.com/1526883/124126545-139fbb80-da7b-11eb-94a2-da707f8f9db1.png)

I'm going to close this for now. Anywhere where it still doesn't work while running the latest version of HTTP Toolkit is a bug - please let me know and I'll look into it :smiley:.

**Closed by pimterry** 2021-07-01 12:47 UTC
