### ISSUE TITLE
Follow link freezes the app

### ISSUE THREAD

**Issue by egi-gjevori** [httptoolkit/httptoolkit#177] opened 2021-09-15 09:25 UTC
When a URL is detected in the response panel it pop ups a button to follow the link. When clicked it freezes the app.
Platform: macOS Big Sur

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2021-09-15 13:50
I can reproduce this, specifically for absolute URLs. Relative URLs seem to show the same popup, but clicking them does nothing at all.

This is a clear bug though, and I think this is actually related to an `about:blank` error I've been trying to hunt down for ages. Thanks so much for reporting this! I'm going to investigate and get this fixed ASAP :+1:

**Comment by pimterry** [comment] 2021-09-15 15:59
Quick update - it's tricky to properly fix this, so I've just disabled autolinking for now to stop other users accidentally freezing their app. I'm still looking into it though, it looks like this is fixable by updating to more recent versions of Monaco. Watch this space!

**Comment by egi-gjevori** [comment] 2021-09-16 06:16
Thanks, no problem by my side. Was not using it but it caught my attention. Removing it works too.

**Comment by pimterry** [comment] 2021-09-16 10:39
Now fixed properly! Absolute URL links in bodies should work again, but this time without anything breaking :smile:. Monaco's been dramatically updated along the way, so all the editors have some other small UX & performance improvements too. Let me know if you spot anything out of the ordinary there! Otherwise I think this issue is sorted, so I'll close it now.

Thanks again for reporting this, this was really useful and it might've been ages before I spotted it for myself! Super helpful :+1:

**Closed by pimterry** 2021-09-16 10:39 UTC
