### ISSUE TITLE
[Bug]: Startup failed

### ISSUE THREAD

**Issue by Masoudj99** [httptoolkit/httptoolkit#487] opened 2023-10-05 05:34 UTC
### Repro steps

*

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11 

### Details of other apps/devices

*

### Error screenshot

https://ibb.co/56RgXFf

### Any other info?

"API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

**Comment by busoldch** [comment] 2023-10-05 06:55
Same for me

**Comment by xKiian** [comment] 2023-10-05 07:52
same for me (i have premium)

**Comment by pimterry** [comment] 2023-10-05 08:49
Dupe of #481, see [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there.

**Closed by pimterry** 2023-10-05 08:49 UTC
Labels: bug
