### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Poloin34** [httptoolkit/httptoolkit#128] opened 2021-02-28 23:12 UTC
It's amazing. I discovered it while searching an answer to a bug with Charles, and the creator linked the httptool website.
I L.O.V.E the auto-setup!!!! After 30 minutes of use, I bought the license and I do not regret it! I'm making a private API of my bank app, and the Export functionnality (premium, it led me to buy it) is just perfect.

Thanks for this super project!!

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2021-03-01 09:11
Thanks @Poloin34! It's lovely to start the week with a message like this, I really appreciate the positive feedback, thanks for getting in touch and for supporting the project.

I am going to close this for now, since it sounds like everything is working as intended :wink:, but feel free to get in touch or file more issues here if you have any other feedback at all.

**Closed by pimterry** 2021-03-01 09:11 UTC
