### ISSUE TITLE
Fresh Chrome doesn't open any site. ERR_PROXY_CERTIFICATE_INVALID is raisen.

### ISSUE THREAD

**Issue by userlond** [httptoolkit/httptoolkit#51] opened 2019-11-21 08:49 UTC
When I open the fresh chrome instance via button on screenshot below, It doesn't open any site, error ERR_PROXY_CERTIFICATE_INVALID is raisen.

![HTTPToolkit Fresh Chrome Button](https://www.dropbox.com/s/8tke92osngcebjf/screenshot%202019-11-21-58%20003.png?raw=1)

![Fresh Chrome Error](https://www.dropbox.com/s/jsz7uc599jjh6cn/screenshot%202019-11-21-58%20002.png?raw=1)

Platform is Windows 7 64bit.

**Comment by pimterry** [comment] 2019-11-21 08:53
I see, thanks for letting me know.

What version of Chrome are you using?

Are there any more details on why the certificate is invalid? For example, in the console or security tab of the browser developer tools, or when you click on the certificate in the address bar?

It's possible that Chrome has changed the requirements for certificates recently, but I haven't noticed that elsewhere.

**Comment by userlond** [comment] 2019-11-21 08:58
Chrome 78.0.3904.108, Windows 7 64bit

**Comment by pimterry** [comment] 2019-11-21 09:07
Ok, thanks. One thing that would be interesting would be to refresh the certificates that were generated, in case there's an issue there somehow.

On Windows, the certificates are stored at `C:\Users\<username>\AppData\Local\httptoolkit\Config\ca.{key,pem}`. Can you try closing the app, moving those files elsewhere, and then starting it again? That should generate new certificates from scratch in the same location. If the new ones work, I'd be very interested to see the old broken ones.

**Comment by userlond** [comment] 2019-11-21 09:22
Steps I've done:
1. Closed the app.
2. Moved ca.{key,pem} files to Desktop directory.
3. Launched the app.
4. New ca.{key,pem} files were generated.
5. Issue with fresh chrome instance still exists.

**Comment by pimterry** [comment] 2019-11-21 11:48
Can you open `chrome://version/` in that broken chrome window, and paste all the text here? That provides some extra info about exactly how Chrome is being run, which might help.

Can you also paste the contents of `chrome://policy` and `chrome://management`, if any? That might have some clues too.

Is there anything else about this machine that might be relevant? Anything you can give me to help hunt this down or reproduce it myself would be super useful :smiley:

**Comment by userlond** [comment] 2019-11-21 12:12
`chrome://version output`

> Google Chrome	78.0.3904.108 (Официальная сборка) (64 бит) (cohort: 78_87_Win)
> Версия	4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
> ОС	Windows 7 Service Pack 1 (Build 7601.24535)
> JavaScript	V8 7.8.279.23
> Flash	24.0.0.189 internal-not-yet-present
> User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
> Командная строка	"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors-spki-list=eLEuuE8npT2BZSed2CFalfQNK0mdfEdIilhVp+pyIUc= --user-data-dir="C:\Users\user\AppData\Local\httptoolkit\Config\chrome-78.0.3904.108" --proxy-server=https://127.0.0.1:8000 --proxy-bypass-list=<-loopback>;http://localhost:8001 --disable-restore-session-state --no-default-browser-check --disable-popup-blocking --disable-translate --start-maximized --disable-default-apps --disable-sync --enable-fixed-layout --no-first-run --noerrdialogs --flag-switches-begin --flag-switches-end http://localhost:8001/hide-chrome-warning
> Путь к исполняемому файлу	C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> Путь к профилю	C:\Users\user\AppData\Local\httptoolkit\Config\chrome-78.0.3904.108\Default

`chrome://policy` reports about "no rules"
![chrome://policy output](https://www.dropbox.com/s/4rkpvbwd9z8dlyj/screenshot%202019-11-21-15%20004.png?raw=1)

`chrome://management/` outputs nothing
![chrome://management/ output](https://www.dropbox.com/s/vfwp2o0soa9ki3b/screenshot%202019-11-21-49%20005.png?raw=1)

**Comment by pimterry** [comment] 2019-11-21 12:26
That's all correct, nothing useful there. Hmm.

* Does Firefox work for you?
* Can you post your current certificate & key from `c:\Users\<username>\AppData\Local\httptoolkit\Config\ca.{key,pem}` here, so I can test with them?
* What happens if you manually import the certificate into Chrome? That means:
  * Go to `chrome://settings/certificates` in the broken Chrome window
  * Click 'Authorities'
  * Click 'Import'
  * Select the current `ca.pem` file.
  * Tick "Trust this certificate for identifying websites"
  * Press ok
  * Try opening another page and see if it works now

Thanks for all your help here, it's difficult to test and reproduce these issues myself without this kind of feedback!

**Comment by userlond** [comment] 2019-11-21 12:52
1. Firefox has same issues, but a little bit different.
I select needed checkbox in dialog, press OK.
![Firefox step 1](https://user-images.githubusercontent.com/7788670/69338688-4e822080-0c96-11ea-9bdb-88479b2bd024.png)
Next Firefox raises certificate error when I try to connect to any site.
![Firefox step 2](https://user-images.githubusercontent.com/7788670/69338810-8b4e1780-0c96-11ea-94d0-e4944ddcc369.png)
2. https://www.dropbox.com/s/s16476aus99vq8b/certificates.7z?dl=0
Archive password is my login.
3. I've tried to follow your steps carefully, result is still the same.

**Comment by pimterry** [comment] 2019-11-21 14:50
Wow, this is a tricky one. I've done some more testing myself, here's a few more options:

* In firefox, if on that error page you click 'Advanced', it should show you some more information. You can share the error code shown at the end, and the contents shown if you click the 'View certificate' button there? Hopefully that will explain why Firefox isn't happy with this.

* Is the clock on your machine definitely showing the correct time & timezone? That could cause issues like these.

* Have you regenerated the certificate since you pasted the `chrome://version` output above? The certificates you sent over don't match the command line there. If you haven't, maybe that's being generated wrong... Can you paste it again? Given the certificates you shared, I'm expecting to see `--ignore-certificate-errors-spki-list=R+vxAnBiGFmqKTdewQqsvmzk7y+akrt+RjqatpxvSms=` within the command line arguments (this is what enables trust for that specific certificate).

* I've put together a custom Chrome command line that trusts _all_ certificates, can you try closing Chrome, then running the below manually with HTTP Toolkit open, and see if it works?
  ```
  "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors --user-data-dir="C:\Users\user\AppData\Local\httptoolkit\Config\chrome-78.0.3904.108" --proxy-server=127.0.0.1:8000 --proxy-bypass-list="<-loopback>;https://localhost:8000" --disable-restore-session-state --no-default-browser-check --disable-popup-blocking --disable-translate --start-maximized --disable-default-apps --disable-sync --enable-fixed-layout --no-first-run --noerrdialogs --flag-switches-begin --flag-switches-end http://amiusing.httptoolkit.tech
  ```

**Comment by userlond** [comment] 2019-11-22 02:37
1. Error code: MOZILLA_PKIX_ERROR_MITM_DETECTED
![image](https://user-images.githubusercontent.com/7788670/69392845-f5ec6b00-0d09-11ea-8144-11047fd2f261.png)
2. Time and timezone is correct.
3. `chrome://version output`

Google Chrome | 78.0.3904.108 (Официальная сборка) (64 бит) (cohort: Stable)
-- | --
Версия | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
ОС | Windows 7 Service Pack 1 (Build 7601.24535)
JavaScript | V8 7.8.279.23
Flash | 24.0.0.189 internal-not-yet-present
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Командная строка | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors-spki-list=eLEuuE8npT2BZSed2CFalfQNK0mdfEdIilhVp+pyIUc= --user-data-dir="C:\Users\user\AppData\Local\httptoolkit\Config\chrome-78.0.3904.108" --proxy-server=https://127.0.0.1:8000 --proxy-bypass-list=<-loopback>;http://localhost:8001 --disable-restore-session-state --no-default-browser-check --disable-popup-blocking --disable-translate --start-maximized --disable-default-apps --disable-sync --enable-fixed-layout --no-first-run --noerrdialogs --flag-switches-begin --flag-switches-end http://localhost:8001/hide-chrome-warning
Путь к исполняемому файлу | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Путь к профилю | C:\Users\user\AppData\Local\httptoolkit\Config\chrome-78.0.3904.108\Default

Certificates: https://www.dropbox.com/s/8epgto23xyixh10/certificate.7z?dl=0
Password is my login.
5. It works :)

![image](https://user-images.githubusercontent.com/7788670/69393393-98f1b480-0d0b-11ea-967a-5f21dd5a44e9.png)

**Comment by pimterry** [comment] 2019-11-23 15:39
Ok, glad that leaves you with a workaround at least.

I'm still a bit stumped on the problem here though. When you have a sec, can you:

* Run Chrome with that working Chrome command
* Go to `https://amiusing.httptoolkit.tech` (note the HTTPS)
* It should say 'Not Secure' in the address bar, but still show the page.
* Click 'Not Secure', click 'Certificate'
* Click 'Details'
* Click the top of the two certificates (should be called HTTP Toolkit CA)
* Click 'Serial number'
* Paste the value here.

That might give us a clue. Otherwise, as an overall summary of what's going on here:

* The app is generating a valid certificate
* The app is passing the right cert details to the browser (in Chrome on the command line, in Firefox via the cert prompt)
* I'm _fairly_ sure that app is then serving the intercepted content with that certificate (and the above serial number should confirm that)
* The browser then looks at the cert it's configured to trust, looks at the same cert being used in the response, and then rejects that cert with no real explanation.

Super weird, and I'm not sure why this might happen. I have heard of this once before (same symptoms, on two different Windows machines owned by the same user) so you're not alone, but it definitely works for the vast majority of users. Something is special about your setup, and I have no idea what it is!

Anyway, let me know the serial number from the above so I can confirm that, and I'll see what other investigation I can do. Any clues you spot or anything else unique about this machine would be very helpful too!

**Comment by userlond** [comment] 2019-11-24 04:02
Hello. I've done what you asked, but seems like there is no "Details" tab or button in certificate dialog (screenshots of tabs are below).

![image](https://user-images.githubusercontent.com/7788670/69489307-64672f80-0ea8-11ea-83f1-1895a105ccb9.png)

![image](https://user-images.githubusercontent.com/7788670/69489331-dccdf080-0ea8-11ea-9837-73820ac8180d.png)

![image](https://user-images.githubusercontent.com/7788670/69489336-f1aa8400-0ea8-11ea-82ee-84839c07046a.png)

I'll type serial number from section below, but this may be not the one you asked:

![image](https://user-images.githubusercontent.com/7788670/69489338-0e46bc00-0ea9-11ea-8db7-4ba5ffeb217b.png)

64 74 b9 ba e5 aa 1a 3b 31 d0 e4 b4 4a 5b 0c db

> Something is special about your setup, and I have no idea what it is!

I've got two account on my PC. One has administrator privilages, another has restricted user privilages. HTTP Toolkit don't run under restricted user (https://github.com/httptoolkit/feedback/issues/50). I'm working under user privilages, so to run HTTP Toolkit I run it as administrator (using Windows UAC), so it starts, but has some issues with certificates, described here.

**Comment by pimterry** [comment] 2022-01-19 10:53
This hasn't been seen in a long time, and there's been a lot of changes in both HTTP Toolkit and Chrome since this was reported originally, so I'm going to assume it's no longer an issue.

Feel free to reply here if you are still seeing this issue, and we can investigate further.

**Closed by pimterry** 2022-01-19 10:53 UTC

**Comment by dantalion7721** [comment] 2024-09-19 10:50
I had the same issue, but my antivirus software caused it. After uninstalling it, HttpToolKit started working again.
