### ISSUE TITLE
[Bug]: Firefox does not load when the button is clicked in HttpToolkit 1.14.1 & 1.14.2

### ISSUE THREAD

**Issue by zoring44** [httptoolkit/httptoolkit#472] opened 2023-09-17 02:17 UTC
### Repro steps

1. Open HttpToolkit.
2. Click on the Firefox button.
3. Observe that Firefox does not open. (I see 1/4 of a loading circle quickly on the Firefox button, and nothing else happens.)
4. Repeatedly clicking the Firefox button does nothing. (The 1/4 of a loading circle quickly appears on the Firefox button, and nothing else happens.)

### How often does this bug happen?

Every time

### The desktop OS you're using

Arch Linux

### Details of other apps/devices

Firefox 117.0.1 - Arch Linux native package

### Any other info?

HttpToolkit 1.14.0 was the last version that worked correctly.

I have tried 1.14.1 and 1.14.2, and they both suffer from this same issue.

I re-downloaded 1.14.0 to test it, and it worked correctly the first time I ran it. However, after the background auto-update kicked in and updated the components to 1.14.1 and I closed and reopened the program, it immediately stopped working.

I also tried reinstalling Arch Linux from scratch, but the issue persisted in my old and new installations.

Here is my log:

--- Launching HTTP Toolkit desktop v1.14.2 ---
INFO: Initialising UI (version 9e0d3e8e8d6d2168e9a0f48c1a1134534b8841cd)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: Server initialization failed TypeError: Failed to fetch
INFO: API store initialized
INFO: Server initialization failed TypeError: Failed to fetch
Config checked in 3 ms
Certificates setup in 8 ms
Standalone server started in 4 ms
Server started in 12 ms
Total startup took 27 ms
(node:5791) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT /var/run/docker.sock
Webextension installed at /tmp/httptoolkit-webextension
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.14.2)
INFO: Rules store initialized
INFO: Events store initialized
INFO: Send store initialized
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.2
Browser cache updated
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.14.2
INFO: Previous server version was 1.14.2
RangeError [ERR_OUT_OF_RANGE]: The value of "start" is out of range. It must be >= 0 && <= 9007199254740991. Received -55
    at new ReadStream (node:internal/fs/streams:196:5)
    at Object.createReadStream (node:fs:2916:10)
    at e.isSnap (/home/user/HttpToolkit/resources/httptoolkit-server/bundle/index.js:944:105965)
    at async e.FreshFirefox.activate (/home/user/HttpToolkit/resources/httptoolkit-server/bundle/index.js:944:76641)
    at async e.ApiModel.activateInterceptor (/home/user/HttpToolkit/resources/httptoolkit-server/bundle/index.js:890:754358)
    at async /home/user/HttpToolkit/resources/httptoolkit-server/bundle/index.js:944:3502
    at async /home/user/HttpToolkit/resources/httptoolkit-server/bundle/index.js:944:2191 {
  code: 'ERR_OUT_OF_RANGE'
}
INFO: Activation result {"success":false,"error":{"code":"ERR_OUT_OF_RANGE","message":"The value of \"start\" is out of range. It must be >= 0 && <= 9007199254740991. Received -55"}}
INFO: Reporting error: Error: API error during activate-interceptor-fresh-firefox: failed to activate interceptor fresh-firefox [object Object]
Shutting down after API call...
Uninstalling webextension from /tmp/httptoolkit-webextension

**Comment by pimterry** [comment] 2023-09-18 09:37
Ah, I see! Yes, this is a bug, I'll get that resolved now.

The issue is that v1.14.1+ now supports intercepting Firefox when it's running within a Snap. It's trickier to reliably detect that than it sounds, so to do so it checks the last 100 bytes of whatever `firefox` resolves to in your PATH to spot the typical Snap wrapper script.

Unfortunately I forgot to handle the 'binary' (presumably just a tiny script here) being under 100 bytes, and that didn't come up in my testing either, but it looks like that's exactly what's happening in your case.

I'll ship an update today, and let you know here once that's live.

**Comment by pimterry** [comment] 2023-09-18 16:54
Server update is now live - next time you run HTTP Toolkit it'll update in the background, and the following time this should be fixed.

Sorry about that! Thanks for reporting this, it's very difficult for me to fully cover all the possible configurations so super helpful to hear about issues like this. Hopefully that resolves this cleanly but do let me know if you're still having any issues at all.

**Closed by pimterry** 2023-09-18 16:54 UTC
Labels: bug

**Comment by zoring44** [comment] 2023-09-18 18:19
@pimterry 

I have downloaded the HTTP Toolkit 1.14.3 and everything is back to working order! Thank you so much for the super quick turnaround time on both the fix and the new release. That is great customer service and software development! :smiley: 

Much love and respect from USA. Have a great day!
