### ISSUE TITLE
[Bug]: Startup failed: "API error during getConfig: GraphQL errors (2)

### ISSUE THREAD

**Issue by adrianmarval** [httptoolkit/httptoolkit#482] opened 2023-10-04 19:23 UTC
### Repro steps

Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### How often does this bug happen?

Every time

### The desktop OS you're using

ubuntu 22.04

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/61595334/325351f0-d9fe-4151-8af2-108c5e91b5f9)

**Comment by pimterry** [comment] 2023-10-05 08:49
Dupe of #481, see [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there.

**Closed by pimterry** 2023-10-05 08:49 UTC
Labels: bug
