### ISSUE TITLE
[Bug]: Configured rules could not be activated, so were reset to default

### ISSUE THREAD

**Issue by TiagoXavi** [httptoolkit/httptoolkit#468] opened 2023-09-14 00:59 UTC
### Repro steps

On Windows:
1. Leave HTTP Toolkit opened and put your pc to sleep or hibernate
2. After returning try creating a new rule on Mock (or activating a disabled one), then the error will occur
3. After pressing "OK" on the message box, another one will pop up immediately

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 10

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/22452335/a63d1a94-e2e6-46c8-a5b2-9d83cee66729)

**Comment by pimterry** [comment] 2023-09-18 12:07
Thanks @TiagoXavi! This is a known issue, see https://github.com/httptoolkit/httptoolkit/issues/345 and https://github.com/httptoolkit/httptoolkit/issues/237 for some more background.

Unfortunately though, I've had problems trying to reproduce this for myself, so it's very difficult to debug and fix! PRs very welcome if you're interested in working on this. 

Fundamentally it's caused by how the [admin client](https://github.com/httptoolkit/mockttp/blob/main/src/client/admin-client.ts) and [admin server](https://github.com/httptoolkit/mockttp/blob/main/src/admin/admin-server.ts) connect - presumably the sleep is causing them to disconnect, but then something causes them to fail to recover afterwards, such that the server gives up and shuts down the session, resulting in the UI becoming unusable as you see here. The relevant code that handles disconnection recovery for the client is [here](https://github.com/httptoolkit/mockttp/blob/b50532a3549ccafc1ff5be2fa21dc8f6f54eab25/src/client/admin-client.ts#L239-L271) and for the server the corresponding API starts [here](https://github.com/httptoolkit/mockttp/blob/b50532a3549ccafc1ff5be2fa21dc8f6f54eab25/src/admin/admin-server.ts#L426). This might be fixable by just extending the retry logic there to try harder, but it's hard to know for sure without being able to reproduce this.

One thing that would be helpful is to see your app logs after this happens - you can access those in the menu under Help -> View HTTP Toolkit logs.

I'm going to close this as a duplicate for now, but do please reply on #345 if you can share logs or any other info about this, or this is something you're interested in helping to fix.

**Closed by pimterry** 2023-09-18 12:07 UTC
Labels: bug

**Comment by Pbmatch** [comment] 2024-02-06 10:59
Hello. I see this error quite often. To catch it, you need to: Probably use a proxy server? The error itself appears when saving or changing and saving new rules in mock. Especially when the body is big. This error occurs 1 time out of 15 saves. The only thing that helps is to turn off the toolkit through the task manager and turn it off node.exe in the same place. Then you can run it again. At the same time, the rules in mock are sometimes erased.
