### ISSUE TITLE
[Bug]: Chromium and Firefox sessions won't start on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by EliasA** [httptoolkit/httptoolkit#392] opened 2023-03-06 14:50 UTC
### Repro steps

1. Open HTTP Toolkit and try to start an intercepted Chromium or Firefox session.
2. In case of Chromium, nothing happens. If Firefox is selected, user is shown the following error:

"Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile."

This happens even after all firefox are killed using "sudo killall firefox" before starting HTTP Toolkit.

Expected behaviour: Chromium and/or Firefox session would start.

### How often does this bug happen?

Every time

### The desktop OS you're using

Ubuntu 22.04.2

### Details of other apps/devices

Thinkpad T450s

### Any other info?

This happens also with a fresh, newly created user with empty browser profiles.

**Comment by pimterry** [comment] 2023-03-06 15:12
Can you open HTTP Toolkit again now, reproduce both issues, and then share the resulting HTTP Toolkit logs? They're in Help -> View HTTP Toolkit logs.

Are you using the Snap versions of Chromium & Firefox? You can tell by running `snap list` and checking if they appear there. That might cause issues like this, since Snap's sandboxing can block some setup processes used here I think.

**Comment by pimterry** [comment] 2023-09-20 14:30
This is now fixed! Both Firefox & Chromium snaps are now correctly supported :smile:. Thanks for reporting this, and do please let me know if you see any issues with this in future.

**Closed by pimterry** 2023-09-20 14:30 UTC
Labels: bug
