### ISSUE TITLE
Feature Request: Ability to add a description to each exchange in 'View'

### ISSUE THREAD

**Issue by mmonj** [httptoolkit/httptoolkit#547] opened 2024-01-21 04:26 UTC
Feature Request: Ability to add a description to each exchange in 'View'

Via the context menu, it would be useful to have an option to add/edit a label for a particular exchange. In the situations where there are a lot of exchanges showing up on the 'View' page, where sometimes you save the exchanges to a HAR file and come back to it a while later, having those descriptions showing up as another column in the row would serve as an extremely helpful reminder as to what the request is actually doing.

Thanks in advance
---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2024-01-22 12:53
Ah, I just saw this - I think I've just replied to an email you also sent me on the same topic.

As noted in the email, I think this is largely a duplicate of https://github.com/httptoolkit/httptoolkit/issues/241. If there's specific extra details about how you think that should work and the overall UX that you'd like to be considered, do please share more details over on that issue.

**Closed by pimterry** 2024-01-22 12:53 UTC
