### ISSUE TITLE
Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"[Bug]: 

### ISSUE THREAD

**Issue by ducnam1200** [httptoolkit/httptoolkit#486] opened 2023-10-05 02:54 UTC
### Repro steps

I downloaded and installed it and when I opened it, it said this error

### How often does this bug happen?

Every time

### The desktop OS you're using

Win 11

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/63830849/c382e169-a585-4617-9240-b50b2258e33f)

**Comment by pimterry** [comment] 2023-10-05 08:49
Dupe of #481, see [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there.

**Closed by pimterry** 2023-10-05 08:49 UTC
Labels: bug
