### ISSUE TITLE
last sent

### ISSUE THREAD

**Issue by HanEmile** [httptoolkit/httptoolkit#529] opened 2023-11-22 13:26 UTC
A column displaying *when* a request was sent would be nice in order to navigate the ever growing history. I'm aware that the space is kind of limited, thus I would suggest making it visible on a certain condition (for example while hovering over the request id (see #528 )) or as a toggle-able column.

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2023-11-23 10:35
I think this is a duplicate of #90, I'll close this - feel free to add votes or share other feedback on that issue.

**Closed by pimterry** 2023-11-23 10:35 UTC
