### ISSUE TITLE
[Bug]: Fail to start on win7 with code 3221225785

### ISSUE THREAD

**Issue by my456l** [httptoolkit/httptoolkit#565] opened 2024-03-11 09:14 UTC
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open the desktop app 2. It crashed saying "HTTP Toolkit hit an error""Server shutdown with code 3221225785." 3. The log last-run.log is empty.

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 7 SP1 64-bit

### Details of other apps/devices

Android phone not connected.

### Error screenshot

![error](https://github.com/httptoolkit/httptoolkit/assets/8111307/e3860a8b-eea8-4d37-9089-d3660cafead8)

### Any other info?

MinGW 8.1.0 x86_64-win32-seh with PATH specified.

**Comment by pimterry** [comment] 2024-03-11 14:06
This is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/243. Please search for existing reports before opening new ones.

This error means that your version of Windows is no longer supported.

On Windows, HTTP Toolkit only supports version 8.1 or newer. Older versions of Windows are no longer supported even by Microsoft, and have not been for many years. In HTTP Toolkit's case, this cannot be supported because some components we use internally (notably Node.js) no longer support Windows 7. You'll need to update to at least Windows 8.1 to use HTTP Toolkit (but I'd recommend moving to Windows 10+, since Windows 8.1 has since reached official end-of-life too in January 2023, and may not be supported either soon). You can check Microsoft's end-of-life support dates for Windows here: https://endoflife.date/windows

**Closed by pimterry** 2024-03-11 14:06 UTC
Labels: bug
