### ISSUE TITLE
[Bug]: Startup failed in Linux Mint

### ISSUE THREAD

**Issue by fpandolfo** [httptoolkit/httptoolkit#490] opened 2023-10-05 12:32 UTC
### Repro steps

1. Open the desktop app
2. Startup will fail

### How often does this bug happen?

Every time

### The desktop OS you're using

Linux Mint 21.2

### Details of other apps/devices

Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### Error screenshot

![tookit startup fail](https://github.com/httptoolkit/httptoolkit/assets/54073536/189eba99-56d4-41fe-ae49-62dd3fb332d8)

### Any other info?

This is the error shown:
"Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config""

**Comment by pimterry** [comment] 2023-10-05 12:34
Dupe of #481, see [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there.

**Closed by pimterry** 2023-10-05 12:34 UTC
Labels: bug
