### ISSUE TITLE
feat suggestion: add MQTT method 

### ISSUE THREAD

**Issue by AboveColin** [httptoolkit/httptoolkit#672] opened 2024-12-10 20:28 UTC
(firstly, i want to say i'm not sure if this can be readable intercepted data)
But it would be nice otherwise to see MQTT traffic for my smart home device traffic.
<img width="727" alt="Screenshot 2024-12-10 at 21 26 53" src="https://github.com/user-attachments/assets/2f587878-8167-45b6-8890-66d072240a33">

---

_Does this affect you too? Click below and add a :+1: to vote for this and help decide where HTTP Toolkit goes next, or [go vote on the other most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment] 2024-12-11 15:10
Thanks @AboveColin! I think this is achieveable and actually it's something that might be made much easier with #645 and its corresponding Android integration, which would give us the necessary metadata to handle this properly. That said, none of this is particularly small or easy and it's not close to the top of my todo list yet.

This is actually a duplicate of #254 though, so I'm going to close it. If you're interested in this, add a :+1: to that issue to vote for it, and if you'd like to contribute to development then take a look through the comments there for some discussion.

**Closed by pimterry** 2024-12-11 15:10 UTC
