### ISSUE TITLE
[Bug]: Stops at loading screen on startup 

### ISSUE THREAD

**Issue by IAMTHEBURT** [httptoolkit/httptoolkit#379] opened 2023-01-18 07:36 UTC
### Repro steps

Macbook AIR M1
1) After opening the app I'm seeing 
"This is taking longer than normal..."
Then nothing happens.

2) Developer tools show
Reporting error: Error: Failed to initialize application
    at index.tsx:132:13
    at Generator.next (<anonymous>)
    at a (app.js?__WB_REVISION__=d909177df3a900b7e8bccc149f34402f:3174:1034) Object

(see screenshots)

Thank you

### How often does this bug happen?

Every time

### The desktop OS you're using

MacBook Air M1 Ventura 13.1

### Error screenshot

<img width="1211" alt="Screenshot 2023-01-18 at 10 33 45" src="https://user-images.githubusercontent.com/68640087/213111138-fa21b319-c23f-4257-a772-b5206594e80d.png">
<img width="1211" alt="Screenshot 2023-01-18 at 10 34 12" src="https://user-images.githubusercontent.com/68640087/213111149-97faedef-642f-4c8a-9312-24fa4a64996e.png">
<img width="1211" alt="Screenshot 2023-01-18 at 10 35 46" src="https://user-images.githubusercontent.com/68640087/213111193-6dc3df89-1a48-4f7b-b2c5-451dfb113f48.png">

**Comment by IAMTHEBURT** [comment] 2023-01-18 07:38
<img width="1211" alt="Screenshot 2023-01-18 at 10 34 12" src="https://user-images.githubusercontent.com/68640087/213111478-a44fd289-0357-4368-ae9f-cd7c8bfdb9fb.png">

**Comment by pimterry** [comment] 2023-01-19 08:32
Hmmmmm, this looks like some part of the server setup is timing out somehow. Can you share the full details of the `127.0.0.1` fetch request that is shows as `pending` in the status column? The two websocket requests pending are totally fine, they stay open indefinitely, but that fetch should really return or fail within a couple of seconds max, and here it's clearly already waited about 10 seconds so something is odd there.

It would also be useful if you could share your log file, which might have some clues what this is waiting for. You can find that by reproducing this issue, then going to Help -> View HTTP Toolkit Logs in the menu.

**Comment by IAMTHEBURT** [comment] 2023-01-22 12:04
This is kinda strange, but it works now. Loads without any freezes. 
Log file doesn't show any errors now. Therefore, if these problems appear again, I will update this topic.
Thanks

**Comment by pimterry** [comment] 2023-01-23 12:06
Hmmm, very strange... Ok, thanks for letting me know.

For now I'm going to close this issue, but do please feel free to reply here with your logs in future if you manage to reproduce this again, and I'll reopen and investigate further.

**Closed by pimterry** 2023-01-23 12:06 UTC
Labels: bug
