### ISSUE TITLE
[Bug]: freeze in loading screen

### ISSUE THREAD

**Issue by eluancardoso** [httptoolkit/httptoolkit#376] opened 2023-01-09 06:08 UTC
### Repro steps

try open and freeze in loading screen

### How often does this bug happen?

Every time

### The desktop OS you're using

windows 10

**Comment by pimterry** [comment] 2023-01-09 07:54
Hi @eluancardoso thanks for reporting this. Can you open the developer tools (View menu -> Toggle Developer Tools) and share screenshots of the console there, and the network panel? You might need to reload the UI (View -> Reload) after opening the tools to see the full details in the network panel there. Hopefully that will have some clues about what the app is waiting for.

**Comment by Deco** [comment] 2023-01-31 08:40
I've been having this exact problem. I started using HTTP Toolkit again a few days ago. I had to reinstall it to get it to work. It seems to work just after being installed, but on any subsequent shutdown & re-opening, it will freeze. I've had to re-install it a dozen times over the past few days just to use it.

There's this error:
![image](https://user-images.githubusercontent.com/95221/215710416-62225e77-d2e0-492c-ab86-933b292b5dab.png)

![image](https://user-images.githubusercontent.com/95221/215710558-b22d29fc-1f5e-4d16-b40f-9331a47f6f5f.png)

I'm not sure if this is the cause.

**Comment by pimterry** [comment] 2023-01-31 11:32
Hi @Deco. Thanks, that's very helpful!

I think what's happened here is that you're running an old version of the desktop shell (<1.1.0, which means before Jan 2021) does that sound possible? This would happen if you're reinstalling from an old download, or if your system is somehow persisting the old version somewhere... And then its updating to the latest version of the UI, which isn't compatible with that, and breaking. That is a bug in the UI (which I'll look at now) but it's still better to be running a new version of the desktop shell anyway so this doesn't happen.

Can you run `navigator.appVersion` in the console of the dev tools, and share the output here? That should confirm the version you're running and the cause of this.

It'd be especially interesting if that shows different values on the first install & the subsequent run, which would mean that somehow some cached data is basically downgrading your app for you somewhere.

If you delete HTTP Toolkit completely, download the latest version from https://httptoolkit.com and then reinstall, does this still happen?

**Comment by Deco** [comment] 2023-01-31 11:58
When it broke, I downloaded the installer directly from the site.

No steps taken / Still broken
`"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HTTPToolkit/1.0.2 Chrome/69.0.3497.106 Electron/4.0.0 Safari/537.36"`

Downloaded and ran installer again / Working
`'5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.12.2 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36'`

Closing then opening again after that / Broken again
`"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HTTPToolkit/1.0.2 Chrome/69.0.3497.106 Electron/4.0.0 Safari/537.36"`

There are two `httptoolkit.exe` files on my drive but both have the same error when I launch them directly:
![image](https://user-images.githubusercontent.com/95221/215752250-888a6f2a-9db6-4c44-9f2e-40687311ef25.png)

Uh oh...
![image](https://user-images.githubusercontent.com/95221/215752349-f1b4a263-2928-4189-ac87-56bf8179e51b.png)

Removing both, then downloading the installer again and running it (which usually works, and it does!):
`'5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.12.2 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36'`

Closing and then opening again... here's the real test... 

Success! It works.
`'5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.12.2 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36'`

Thanks for pointing me down the right path. I hope the above info helps other users.

**Comment by pimterry** [comment] 2023-01-31 17:31
Great, thanks for testing that! Yes, I have no idea why really, but it looks like the old v4 install was somehow downgrading your new version each time. Very odd...

Anyway, glad that's sorted, you shouldn't see issues with this again. I've also now added a polyfill and tested that everything else works correctly, so others who do end up running an older desktop release shouldn't hit this issue either.

I'll close this issue now. If you or anybody else runs into more issues like this, do please let me know!

**Closed by pimterry** 2023-01-31 17:31 UTC
Labels: bug
