### ISSUE TITLE
HTTP Toolkit could not start

### ISSUE THREAD

**Issue by 89z** [httptoolkit/httptoolkit#171] opened 2021-08-26 21:24 UTC
I closed the program, and everything seemed normal. However when I reopen the program, I get this:

~~~
HTTP Toolkit could not start

HTTP Toolkit's local management port (45457) is already in use.

Do you have another HTTP Toolkit process running somewhere?
Please close the other process using this port, and try again.
~~~

After I get the error, I close again and check running programs, and I dont see any instances of `HTTP Toolkit.exe`. Should I be looking for a different program?

**Comment by pimterry** [comment] 2021-09-06 15:25
> every single time

I've a bunch done more testing, but I still can't reproduce this reliably! I've seen it once or twice in the past, but only very very rarely, never consistently like you're describing.

I'm testing using Windows 10.0.19043, and every time I exit HTTP Toolkit it shuts down Node.js correctly. It doesn't seem to matter whether I've launched anything or what I'm doing, I can't find any consistent triggers that break the shutdown process.

Are there any other clues you can give me to hunt this down? Does it happen if you launch HTTP Toolkit, wait a few seconds for it to start up but don't click anything, and immediately close it? Are you closing it directly from the window toolbar? If you launch the HTTP Toolkit from the command line, is anything interesting shown in the output there? Anything more specific about your system or what you're doing that might explain why this is happening in your case but not elsewhere would be helpful.

> In the event of an improper shutdown (as is currently happening consistently), upon start of a new process, a search should be done for any zombie processes.

Unfortunately this is difficult because users could very well be running other `node.exe` processes that they don't want killed unexpectedly, and scanning & interrogating all the running processes to check is also expensive and we'd need to do it before the app could start, so there'd be a noticeable performance hit every time. I'd much rather focus on hunting down the root cause to ensure the process isn't left behind at all.

**Comment by 89z** [comment] 2021-09-06 15:28
I am using Windows 10.0.18363, not sure if that makes a difference.

**Comment by shirshak55** [comment] 2021-09-28 06:33
I think it happens in case if program is not properly shut down right? 

@pimterry  Actually we can scan for node programs that is ran by HTTP Toolkit only.  In past, I used to use wmic to handle such esoteric cases but I think this can be doable in windows too. I will think about it more.

**Comment by pimterry** [comment] 2021-10-20 21:48
Fair enough, of course you're welcome to do that, but it is going to break things! I too have had issues using the default command-line utilities on Windows before, but the more common & compatible approach would be to put replacements on the PATH before System32, rather than removing System32 entirely. Git Bash offers to take that approach when installing GNU utilities, for example (but even then, that comes with a large warning that not having the standard versions of utilities like find & sort in your PATH will break many Windows scripts & applications).

Anyway, yes, of course you can do what you like. Right now though that's not a supported environment.

Of course, a free way to widen compatibility is always nice, so I'd be happy to include a quick fix to support this by manually fixing the PATH variable at start up within [the desktop wrapper](https://github.com/httptoolkit/httptoolkit-desktop/blob/master/src/index.ts). I think just checking whether the correct System32 path given those env vars is included in $PATH and appending it if not should be sufficient. I'm not sure when I'll have time to get to that, but if that would be useful to you in the meantime then you're welcome to open a PR (just in case you weren't aware: HTTP Toolkit Pro is totally free for all open-source contributors - more background [here](https://httptoolkit.tech/blog/free-as-in-beer/#new-decade-resolutions)).

**Comment by pimterry** [comment] 2021-10-21 12:19
@shirshak55 I'm not totally sure what you mean. I don't think @89z is working on this, and I'm not either, is that's what you're asking?

If you want to take a look at this and open a PR then feel free, that would be very welcome.

**Closed** 2021-11-16 18:31 UTC
