### ISSUE TITLE
[Bug]: I keep on getting Certificated Rejected even tho I have a system certificate for apps that don't trust user certificates .

### ISSUE THREAD

**Issue by BigScriptus** [httptoolkit/httptoolkit#387] opened 2023-02-12 15:50 UTC
### Repro steps

Install the certificate as system 
open an app that only trust's system certificates 

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Details of other apps/devices

![image](https://user-images.githubusercontent.com/55254772/218321487-88b7632c-6c6d-495c-ad9c-0615a33c7c1a.png)
I am intercepting app traffic from an android 13 device

### Error screenshot

![image](https://user-images.githubusercontent.com/55254772/218321430-f1048722-283b-4373-8e3a-798812bf974c.png)

**Comment by pimterry** [comment] 2023-02-13 12:43
There's a few different things that could cause this, but by far the most likely is that the app is using certificate pinning. In that case, even though the HTTP Toolkit system certificate is installed, the app will refuse to trust it. There's more detail on this and how to defeat it here: https://httptoolkit.com/blog/frida-certificate-pinning/

The easiest way to tell if this is the cause is to look at the rest of the traffic. If all traffic from all apps is blocked, then it's probably a more general setup issue. If most traffic from most apps is intercepted successfully though, and just a few requests fail like this, then the device is probably set up correctly and so the issue is likely due to certificate pinning.

Does that sound like what you're seeing? If so, you can use Frida with the instructions from the post above, and that should solve your issues in most cases.

**Comment by pimterry** [comment] 2023-02-20 09:52
Closing for now. I strongly suspect the Frida post here does indeed fix this issue, but if that's not what's happening then do please share more info here and I can reopen this.

**Closed by pimterry** 2023-02-20 09:52 UTC
Labels: bug

**Comment by nutterthanos** [comment] 2023-05-01 02:33
> Closing for now. I strongly suspect the Frida post here does indeed fix this issue, but if that's not what's happening then do please share more info here and I can reopen this.

frida seems to not work lately
C:\Users\conno\frida-server-16.0.2-windows-x86.exe>frida -U -l ./frida-script.js.1 -f com.android.vending
     ____
    / _  |   Frida 16.0.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM A715F (id=192.168.0.6:33313)
Spawned `com.android.vending`. Resuming main thread!
Error: VM::AttachCurrentThread failed: -1
    at o (frida/node_modules/frida-java-bridge/lib/result.js:4)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:27)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:15)
    at st (frida/node_modules/frida-java-bridge/lib/android.js:534)
    at ze (frida/node_modules/frida-java-bridge/lib/android.js:202)
    at Oe (frida/node_modules/frida-java-bridge/lib/android.js:16)
    at _tryInitialize (frida/node_modules/frida-java-bridge/index.js:29)
    at _ (frida/node_modules/frida-java-bridge/index.js:21)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:332)
    at call (native)
    at o (/_java.js)
    at <anonymous> (/_java.js)
    at <anonymous> (frida/runtime/java.js:1)
    at call (native)
    at o (/_java.js)
    at r (/_java.js)
    at <eval> (frida/runtime/java.js:3)
    at _loadJava (native)
    at get (frida/runtime/core.js:130)
    at <anonymous> (C:\Users\conno\frida-server-16.0.2-windows-x86.exe\frida-script.js.1:57)
    at apply (native)
    at <anonymous> (frida/runtime/core.js:51)

**Comment by nutterthanos** [comment] 2023-05-01 03:51
httptoolkit out of box on android at least on my device didn't have any trouble with ssl pinning with most if not all google apps now it does not even work
