### ISSUE TITLE
[Bug]: Startup failed: "API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### ISSUE THREAD

**Issue by devadiab** [httptoolkit/httptoolkit#495] opened 2023-10-05 14:46 UTC
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

Just open the http toolkit and you will get the error

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

### Error screenshot

![image](https://github.com/httptoolkit/httptoolkit/assets/7278576/e908ab49-707a-4d6a-96d6-452c8c7cf44b)

**Comment by devadiab** [comment] 2023-10-05 14:47
And here is the network requests for the application:
![image](https://github.com/httptoolkit/httptoolkit/assets/7278576/39d03357-7297-406e-9ce1-884cb1dee8fc)

**Comment by pimterry** [comment] 2023-10-05 14:47
> [x] I have checked for existing reports of this issue

You haven't checked for existing reports - this is clearly a dupe of #481 which contains the exact same error message.

See [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there which will resolve this for you.

In future please check for existing issues before filing new ones! It saves you and everybody else lots of time and hassle.

**Closed by pimterry** 2023-10-05 14:47 UTC
Labels: bug

**Comment by devadiab** [comment] 2023-10-05 14:48
Thanks it worked
