### ISSUE TITLE
[Bug]: Startup failed: "APl error during getConfig: GrapnOl errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config"

### ISSUE THREAD

**Issue by sellgoldman** [httptoolkit/httptoolkit#484] opened 2023-10-04 23:05 UTC
### Repro steps

App httptoolkit won't turn on

### How often does this bug happen?

Only once

### The desktop OS you're using

Windows 10

### Error screenshot

![photo_2023-10-05_01-59-30](https://github.com/httptoolkit/httptoolkit/assets/147006509/69df976e-8d30-47d1-949f-7ac3f42ec493)

### Any other info?

This problem occurs on multiple computers at the same time. Came from nowhere

**Comment by mahmozilla** [comment] 2023-10-05 00:02
its happening with me too. here are my logs

--- Launching HTTP Toolkit desktop v1.14.3 ---
INFO: Initialising UI (version 504213ce08f02af2c7faec2e9681e7dbabf3874d)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
Config checked in 28 ms
Certificates setup in 16 ms
Standalone server started in 10 ms
Server started in 21 ms
Total startup took 76 ms
(node:4844) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
INFO: Service worker loaded
Mock session started, http on port 8000, webrtc enabled
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
httptoolkit-server: Updating CLI... fetching manifest
ERROR: [object Object],[object Object]
INFO: Reporting error: Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config [object Object]
ERROR: Uncaught (in promise) Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config
ERROR: Uncaught (in promise) Error: API error during getConfig: GraphQL errors (2): Cannot read properties of undefined (reading 'apiConfig') at systemProxy, Cannot read properties of undefined (reading 'apiConfig') at config
httptoolkit-server: Updating CLI... already on latest version: 1.14.4
Webextension installed at C:\Users\user\AppData\Local\Temp\httptoolkit-webextension
INFO: Previous server version was 1.14.4

**Comment by pimterry** [comment] 2023-10-05 08:49
Dupe of #481, see [the solution](https://github.com/httptoolkit/httptoolkit/issues/481#issuecomment-1748401917) discussed there.

**Closed by pimterry** 2023-10-05 08:49 UTC
Labels: bug

**Comment by sellgoldman** [comment] 2023-10-05 09:56
its ok, thanks
